cmake_minimum_required(VERSION 3.25)
project(MSIMEBackendNative LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(BUILD_TESTING OFF CACHE BOOL "Build Engine tests" FORCE)
find_package(nlohmann_json 3.11 CONFIG REQUIRED)
add_subdirectory(../third_party/MSIME-Engine engine)
add_executable(msime-engine main.cpp)
target_link_libraries(msime-engine PRIVATE MetasequoiaIme::Engine nlohmann_json::nlohmann_json)
