cmake_minimum_required(VERSION 3.25)
project(MSIMEBackendNative LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(BUILD_TESTING OFF CACHE BOOL "Build Engine tests" FORCE)
find_package(nlohmann_json 3.11 CONFIG REQUIRED)
add_subdirectory(../third_party/MSIME-Engine engine)
add_executable(msime-engine main.cpp)
target_link_libraries(msime-engine PRIVATE MetasequoiaIme::Engine nlohmann_json::nlohmann_json)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Static native dependencies" FORCE)
set(ENABLE_GTEST OFF CACHE BOOL "" FORCE)
set(ENABLE_BENCHMARK OFF CACHE BOOL "" FORCE)
set(OPENCC_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory(../third_party/opencc opencc)
target_link_libraries(msime-engine PRIVATE OpenCC::OpenCC)
set(CPP_PINYIN_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(CPP_PINYIN_INSTALL OFF CACHE BOOL "" FORCE)
add_subdirectory(../third_party/cpp-pinyin cpp-pinyin)
target_link_libraries(msime-engine PRIVATE cpp-pinyin::cpp-pinyin)
